export const tastings = [
  {
    miniImage: "/tastings/mini/medovaya.jpg",
    image: "/tastings/webp/medovaya.webp",
    name: "Медовая",
    description: "Наи фирменные бархатные медовые коржи с пикантным сметанным кремом.",
    ingredients: "Мука, сахар, яйцо, мёд, сливочное масло, сгущённое молоко, сметана, сода пищевая, уксус.",
    tastingPrice: 0,
    isForAllTiers: true, 
  },
  {
    miniImage: "/tastings/mini/snickers.jpg",
    image: "/tastings/webp/snickers.webp",
    name: "Сникерс",
    description: "Всё самое лучшее от знаменитого батончика, шоколадные коржи с шоколадным кремом в комбинации со слегка солоноватым крем-чизом и вкуснейшей прослойкой из карамели с арахисом",
    ingredients: "Яйцо, сахар, пищевая сода, сметана, мука, какао, сливки, шоколад, сыр творожный, карамель, арахис",
    tastingPrice: 0,
    isForAllTiers: true, 
  },
  {
    miniImage: "/tastings/mini/shokoladnaya.jpg",
    image: "/tastings/webp/shokoladnaya.webp",
    name: "Шоколадная",
    description: "Традиционный шоколадный бисквит и супершоколадный крем на основе сливочного масла и элитного какао.",
    ingredients: "Мука, сахар,яйцо,сливочное масло, цельное сгущенное молоко, какао-порошок, подсолнечное масло, коньяк, ванилин.",
    tastingPrice: 0,
    isForAllTiers: true, 
  },
  {
    miniImage: "/tastings/mini/rafaello.jpg",
    image: "/tastings/webp/rafaello.webp",
    name: "Рафаэлло",
    description: "Нежный сливочный крем с добавлением пюре из мякоти кокоса, классический пропитанный бисквит покрытый хрустящим слоем из бельгийской вафли, шоколада и фундука.",
    ingredients: "Мука, сахар, яйцо, сливочное масло, сливки молочные 35%, сыр творожный, сахарная пудра, кокосовое пюре, карамелизированная вафля, фундук дробленный, бельгийский шоколад.",
    tastingPrice: 0,
    isForAllTiers: true, 
  },
  {
    miniImage: "/tastings/mini/orehovaya.jpg",
    image: "/tastings/webp/orehovaya.webp",
    name: "Ореховая",
    description: "Классический бисквит щедро пропитанный сиропом, крем на основе натурального сливочного масла, варенной сгущенки с добавлением дробленного фундука.",
    ingredients: "Мука, сахар, яйцо, сливочное масло, орех фундук, цельное сгущённое молоко, сгущённое молоко вареное, коньяк.",
    tastingPrice: 0,
    isForAllTiers: true, 
  },
  {
    miniImage: "/tastings/mini/esterkhazy.jpg",
    image: "/tastings/webp/esterkhazy.webp",
    name: "Эстерхази",
    description: "Тонкие белково-ореховые коржи с добавлением дробленного фундука, прослоенный нежным заварным кремом с добавлением лимонной цедры.",
    ingredients: "Мука, сахар, яйцо, молоко, сливочное масло, сгущенное молоко, орех фундук, лимон.",
    tastingPrice: 0,
    isForAllTiers: true, 
  },
  {
    miniImage:"/tastings/mini/pancho.jpg",
    image:"/tastings/webp/pancho.webp",
    name:"Панчо",
    description: "Великолепное сочетание шоколадного и классического бисквита с вкуснейшим сметанным кремом, с добавлением грецкого ореха и консервированного ананаса.",
    ingredients: " Мука, сахар, яйцо, какао, сметана, грецкий орех, консервированный ананас, масло сливочное, сода, ванилин.",
    tastingPrice: 0,
    isForAllTiers: false, 
  },
  {
    miniImage:"/tastings/mini/molochnaya-devochka.jpg",
    image:"/tastings/webp/molochnaya-devochka.webp",
    name:"Молочная девочка",
    description: "Самая нежная начинка в нашей коллекции. Тонкие и воздушные коржи на основе сгущенного молока с легким и нежным сметанным кремом.",
    ingredients: "Молоко сгущенное, яйцо, мука, сметана, сливки животные, сахар.",
    tastingPrice: 0,
    isForAllTiers: false, 
  },
  {
    miniImage:"/tastings/mini/klubnichnaya-devochka.jpg",
    image:"/tastings/webp/klubnichnaya-devochka.webp",
    name:"Клубничная девочка",
    description: "Самая нежная начинка в нашей коллекции. Тонкие и воздушные коржи на основе сгущенного молока с легким и нежным сметанным кремом с прослойкой из клубники.",
    ingredients: "Молоко сгущеное, яйцо, мука, сметана, сливки животные, клубника, сахар.",
    tastingPrice: 0,
    isForAllTiers: false, 
  },
  {
    miniImage:"/tastings/mini/kbarhat.jpg",
    image:"/tastings/webp/kbarhat.webp",
    name:"Красный бархат",
    description: "Невероятно нежный бисквитный торт с сметанным кремом. Цвет торта подчеркнет торжественность момента.",
    ingredients: "Мука, сахар, яйцо, какао, сметана, сахарная пудра, крахмал,кефир, подсолнечное масло, сода, разрыхлитель, соль, ванилин, пищевой краситель.",
    tastingPrice: 0,
    isForAllTiers: false, 
  },
  {
    miniImage: "/tastings/mini/yantarny.jpg",
    image: "/tastings/webp/yantarny.webp",
    name: "Янтарная",
    description: "Морковные коржи с добавлением грецкого ореха, ноткой корицы в сочетании с лёгким кремом и кули из солнечного мандарина.",
    ingredients: "Яйцо, сахар, масло растительное, морковь, орехи грецкие, мука, соль, корица, пюре мандариновое, сыр творожный, масло сливочное",
    tastingPrice: 300,
    isForAllTiers: true, 
  },
  {
    miniImage: "/tastings/mini/cheremukha-malina.jpg",
    image: "/tastings/webp/cheremukha-malina.webp",
    name: "Черемуха-малина",
    description: "Ненавязчивая текстура пропитанного и ароматного бисквита с добавлением черемуховой муки придает миндальное послевкусие в взрывном сочетании с ярким малиновым конфитюром и нежным сметанным кремом.",
    ingredients: "Яйцо, сахар, масло растительное, мука черемуховая, мука пшеничная, сыр твороженный, сметана, пюре малиновое.",
    tastingPrice: 300,
    isForAllTiers: true, 
  },
  {
    miniImage:"/tastings/mini/muss-mango-marakuya.jpg",
    image:"/tastings/webp/muss-mango-marakuya.webp",
    name:"Манго-маракуйя",
    description: "Нежнейший освежающий мусс на основе пюре манго и маракуйи с добавлением кусочков манго с ванильным бисквитом.",
    ingredients: "пюре манго, пюре маракуйи, консервированный манго, яйца, сахар ,мука ,желатин, сливки 35%",
    tastingPrice: 300,
    isForAllTiers: false, 
  },
  {
    miniImage:"/tastings/mini/muss-klubnichniy.jpg",
    image:"/tastings/webp/muss-klubnichniy.webp",
    name:"Клубничный мусс",
    description: "Нежный мусс на основе натуральных сливок и клубники, прослоен тонким классическим бисквитом.",
    ingredients: "Мука, сахар, яйцо, сливки животные, клубника свежая замороженная, желатин, ванилин.",
    tastingPrice: 0,
    isForAllTiers: false, 
  },
  {
    miniImage:"/tastings/mini/3-shokolada.jpg",
    image:"/tastings/webp/3-shokolada.webp",
    name:"Три Шоколада",
    description: "Трехслойный мусс на основе бельгийского шоколада, с шоколадным бисквитом. Ценители шоколада будут в восторге.",
    ingredients: "Белый шоколад, молочный шоколад, горький шоколад, молочные сливки, творожный сыр, яйцо, сахар, мука, коньяк, желатин.",
    tastingPrice: 300,
    isForAllTiers: false, 
  },
  {
    miniImage: "/tastings/mini/fistashka-malina.jpg",
    image: "/tastings/webp/fistashka-malina.webp",
    name: "Фисташка-малина",
    description: "Нежнейшее сочетание малинового и фисташкового крема с прослойкой из освежающего малинового кули и легким хрустящим слоем.",
    ingredients: "Бисквит, бельгийский шоколад, фисташки, пюре малина, сыр творожный, пата фисташковая, сливки, сахар",
    tastingPrice: 300,
    isForAllTiers: true, 
  },
  {
    miniImage: "/tastings/mini/banana-brownie.jpg",
    image: "/tastings/webp/banana-brownie.webp",
    name: "Банановый брауни",
    description: "Коржи на основе бельгийского шоколада, нежнейший крем на основе сливочного сыра, натуральных сливок с добавлением свежего банана.",
    ingredients: "Бельгийский шоколад, мука, яйцо, сахар, тростниковый сахар, сливочное масло, творожный сыр, сливки животные, сахарная пудра, бананы.",
    tastingPrice: 300,
    isForAllTiers: true, 
  },
  {
    miniImage:"/tastings/mini/malina-creamcheese.jpg",
    image:"/tastings/webp/malina-creamcheese.webp",
    name:"Малиновый крем-чиз",
    description: "Пропитанный шоколадный бисквит, прослоенный вкуснейшим сырным кремом с вареньем из свежей малины.",
    ingredients: "Мука, сахар, яйцо,какао-порошок (высшей категории), сливки животные, сыр сливочный творожный, сахарная пудра, ванилин.",
    tastingPrice: 0,
    isForAllTiers: false, 
  },
  {
    miniImage:"/tastings/mini/tiramisu.jpg",
    image:"/tastings/webp/tiramisu.webp",
    name:"Тирамису",
    description: "Итальянский десерт, ставший бестеллером всех кафе, везде он свой. У нас, воздушный мусс на сливочном сыре с прослойкой из бисквита и кофейной пропиткой.",
    ingredients: "Мука, сахар, яичный желток, сливки молочные 35%, сыр творожный , ликер Бэйлиз, кофе растворимый, желатин.",
    tastingPrice: 300,
    isForAllTiers: false, 
  },
];